image: node:16.15.0-slim

stages:
  - testing
  - build
  - deploy

variables:
  POSTGRES_DB: unipiece
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  SERVER_HOST: 44.209.198.71
  SERVER_USER: bad_project
  PROJECT_ROOT: ~/unipeice-FRD-Project
  WEB_SERVER_ROOT: server
  WEB_SERVER_NAME: Unipiece

testing:
  stage: testing

  services:
    - postgres:14.3-alpine

  artifacts:
    paths:
      - $WEB_SERVER_ROOT/node_modules

  before_script:
    - pwd
    - npm i -g pnpm
    - pnpm i

  # script:
  #   - npm test

build:
  stage: build
  dependencies:
    - testing

  artifacts:
    paths:
      - $WEB_SERVER_ROOT/dist

  before_script:
    - cd $WEB_SERVER_ROOT
    - npm install

  script:
    - npm run build

deploy:
  stage: deploy
  image: ubuntu:22.04

  dependencies:
    - build

  before_script:
    - apt update
    - apt install --yes rsync openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST > ~/.ssh/known_hosts
    - echo "Host server" >> ~/.ssh/config
    - echo "  Hostname $SERVER_HOST" >> ~/.ssh/config
    - echo "  User $SERVER_USER" >> ~/.ssh/config
    - echo "  IdentityFile ~/.ssh/id_rsa " >> ~/.ssh/config
    - cat ~/.ssh/config
    - pwd
    - ls -la
    - cd $WEB_SERVER_ROOT

  script:
    - rsync -SavLP dist "server:$PROJECT_ROOT/$WEB_SERVER_ROOT"
    - ssh server "
      source ~/.nvm/nvm.sh &&
      cd $PROJECT_ROOT/$WEB_SERVER_ROOT &&
      git fetch &&
      git checkout $CI_COMMIT_SHA &&
      pnpm i --prod &&
      cd dist &&
      npx knex migrate:latest &&
      pm2 start --name $WEB_SERVER_NAME server.js ||
      pm2 reload $WEB_SERVER_NAME
      "
